version: '3'
services:

  prd-nextcloud-app:
    image: docker-registry.theautomation.nl/coen/prd-nextcloud-app:latest
    container_name: prd-nextcloud-app
    networks:
      - home-services
    ports:
      - 8080:80
    volumes:
      - prd-nextcloud-app-data:/var/www/html
    env_file: prd-nextcloud-app.env
    depends_on:
      - prd-nextcloud-db
      - prd-nextcloud-redis

  prd-nextcloud-db:
    image: docker-registry.theautomation.nl/coen/prd-nextcloud-db:latest
    container_name: prd-nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - home-services
    volumes:
      - prd-nextcloud-db-data:/var/lib/mysql
    env_file: prd-nextcloud-db.env

  prd-nextcloud-redis:
    image: docker-registry.theautomation.nl/coen/prd-nextcloud-redis:latest
    container_name: prd-nextcloud-redis
    restart: always
    networks:
      - home-services

  prd-nextcloud-cron:
    image: docker-registry.theautomation.nl/coen/prd-nextcloud-app:latest
    container_name: prd-nextcloud-cron
    restart: always
    volumes:
      - prd-nextcloud-app-data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - prd-nextcloud-db
      - prd-nextcloud-redis

# VOLUMES
volumes:

  prd-nextcloud-db-data:
    name: prd-nextcloud-db-data
  prd-nextcloud-app-data:
    name: prd-nextcloud-app-data

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16
